//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finlapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsersDBEntities2 : DbContext, IUsersDBEntities2Context
    {
        public UsersDBEntities2()
            : base("name=UsersDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<kkk> kkks { get; set; }
        public virtual DbSet<Project_members> Project_members { get; set; }
        public virtual DbSet<project_tasks> project_tasks { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<timesheet> timesheets { get; set; }
        public virtual DbSet<timesheet_analysis> timesheet_analysis { get; set; }




        public void MarkAsModified(employee item)
        {
            Entry(item).State = EntityState.Modified;
        }

        public void MarkAsModified(C__MigrationHistory item)
        {
            Entry(item).State = EntityState.Modified;
        }
        public void MarkAsModified(AspNetUser item)
        {
            Entry(item).State = EntityState.Modified;
        }
        public void MarkAsModified(AspNetRole item)
        {
            Entry(item).State = EntityState.Modified;
        }
        public void MarkAsModified(AspNetUserClaim item)
        {
            Entry(item).State = EntityState.Modified;
        }
        public void MarkAsModified(AspNetUserLogin item)
        {
            Entry(item).State = EntityState.Modified;
        }
        public void MarkAsModified(project item)
        {
            Entry(item).State = EntityState.Modified;
        }
        public void MarkAsModified(project_tasks item)
        {
            Entry(item).State = EntityState.Modified;
        }
        public void MarkAsModified(Project_members item)
        {
            Entry(item).State = EntityState.Modified;
        }
        public void MarkAsModified(timesheet item)
        {
            Entry(item).State = EntityState.Modified;
        }

        public void MarkAsModified(timesheet_analysis item)
        {
            Entry(item).State = EntityState.Modified;
        }

    }
}
