//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finlapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public timesheet()
        {
            this.timesheet_analysis = new HashSet<timesheet_analysis>();
        }
    
        public int id { get; set; }
        public int project_members_id { get; set; }
        public System.DateTime date { get; set; }
        public int hours { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public string comments_reviwer { get; set; }
        public string comments_manager { get; set; }
        public Nullable<int> resubmit_flag { get; set; }
        public Nullable<int> projecttask_id { get; set; }
    
        public virtual Project_members Project_members { get; set; }
        public virtual project_tasks project_tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timesheet_analysis> timesheet_analysis { get; set; }
    }



    public class timesheetsubmission
    {
        public int id { get; set; }

        public int hours { get; set; }
        public string description { get; set; }

    }


    public class timesheetreview
    {
        public int id { get; set; }

        public string status { get; set; }
        public string comments { get; set; }

    }

    public class managertimesheetreview
    {
        public int id { get; set; }

        public string status { get; set; }
        public string comments { get; set; }

        public int flag { get; set; }

    }


    public class projectstatus
    {
        public int id { get; set; }

        public string status { get; set; }
       

    }



}
