//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finlapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheet_analysis
    {
        public int timesheet_id { get; set; }
        public Nullable<int> resubmit_count { get; set; }
        public Nullable<int> reject_count { get; set; }
        public int id { get; set; }
    
        public virtual timesheet timesheet { get; set; }
    }
}
